# Generated by Django 5.0.6 on 2024-11-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plbl_filter', models.CharField(choices=[('Balance Sheet Assets', 'Balance Sheet Assets'), ('Balance Sheet Liabilities', 'Balance Sheet Liabilities'), ('P And L Direct Income ', 'P And L Direct Income'), ('P And L Indirect Income', 'P And L Indirect Income'), ('P And L Direct Expense ', 'P And L Direct Expense'), ('P And L Indirect Expense', 'P And L Indirect Expense'), ('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], max_length=100)),
                ('name', models.CharField(choices=[('Bank Accounts', 'Bank Accounts'), ('Bank OCC A/C', 'Bank OCC A/C'), ('Bank OD A/C', 'Bank OD A/C'), ('Branch/Division', 'Branch/Division'), ('Capital A/C', 'Capital A/C'), ('Cash in Hand', 'Cash in Hand'), ('Current Assets', 'Current Assets'), ('current Liabilities', 'current Liabilities'), ('Deposits(Assets)', 'Deposits(Assets)'), ('Direct Expense', 'Direct Expense'), ('Direct Income', 'Direct Income'), ('Duties & Taxes', 'Duties & Taxes'), ('Expense(Direct)', 'Expense(Direct)'), ('Expense(Indirect)', 'Expense(Indirect)'), ('Fixed Assets', 'Fixed Assets'), ('Income(Direct)', 'Income(Direct)'), ('Indirect Expense', 'Indirect Expense'), ('Indirect Income', 'Indirect Income'), ('Income(Indirect)', 'Income(Indirect)'), ('Investments', 'Investments'), ('Loans & Advances(Assets)', 'Loans & Advances(Assets)'), ('Loan(Liabilities)', 'Loan(Liabilities)'), ('Misc. Expenses(Assets)', 'Misc. Expenses(Assets)'), ('Provisions', 'Provisions'), ('Purchase Accounts', 'Purchase Accounts'), ('Reserves And Surplus', 'Reserves And Surplus'), ('Retained Earnings', 'Retained Earnings'), ('Sales Accounts', 'Sales Accounts'), ('Secured Loans', 'Secured Loans'), ('Stock_in_Hand', 'Stock_in_Hand'), ('Sundry Creditors', 'Sundry Creditors'), ('Sundry Debtors', 'Sundry Debtors'), ('Suspense Accounts', 'Suspense Accounts'), ('Unsecured Loans ', 'Unsecured Loans')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('Attendance', 'Attendance'), ('Contra', 'Contra'), ('Credit Note', 'Credit Note'), ('Debit Note', 'Debit Note'), ('Delivery Note', 'Delivery Note'), ('Job work in order', 'Job work in order'), ('Job work out order', 'Job work out order'), ('Journal', 'Journal'), ('Material In', 'Material In'), ('Material Out', 'Material Out'), ('Memorandum', 'Memorandum'), ('Payment', 'Payment'), ('PayRoll', 'PayRoll'), ('Physical Stock', 'Physical Stock'), ('Purchase', 'Purchase'), ('Purchase Order', 'Purchase Order'), ('Receipt', 'Receipt'), ('Receipt Note', 'Receipt Note'), ('Rejections In', 'Rejections In'), ('Rejections Out', 'Rejections Out'), ('Reversing Journal', 'Reversing Journal'), ('Sales', 'Sales'), ('Sales Order', 'Sales Order'), ('Stocks Journal', 'Stocks Journal')], max_length=20)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='client_ledger_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_group', models.CharField(max_length=60)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client_ledger_group')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting_app.voucher')),
            ],
        ),
    ]
