# Generated by Django 4.2.4 on 2024-11-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_app', '0001_initial'),
        ('purchase_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RD_Unapproved_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_unapproved_stock', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(max_length=150, null=True)),
                ('raw_materials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.rawmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='RD_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_stock', models.IntegerField(null=True)),
                ('unapproved_stock', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('raw_materials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.rawmaterialsstock')),
            ],
        ),
    ]
