# Generated by Django 5.0.6 on 2024-11-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd_unapproved_stock',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
