# Generated by Django 4.1.3 on 2024-11-28 05:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Present', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('basic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('pincode', models.CharField(blank=True, max_length=9, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=120, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('employee_blood_groups', models.CharField(blank=True, choices=[('AB+', 'AB+'), ('B+', 'B+'), ('A+', 'A+'), ('O+', 'O+'), ('AB-', 'AB-'), ('B-', 'B-'), ('A-', 'A-'), ('O-', 'O-')], default='AB+', max_length=100)),
                ('pf_no', models.CharField(blank=True, max_length=22, unique=True)),
                ('employee_esi_no', models.CharField(blank=True, max_length=17, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('qualification_file', models.FileField(blank=True, null=True, upload_to='qualification_files/')),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('experience_file', models.FileField(blank=True, null=True, upload_to='experience_files/')),
                ('id_proof_type', models.CharField(choices=[('AADHAR', 'AADHAR'), ('PASSPORT', 'PASSPORT'), ('PAN CARD', 'PAN CARD'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('other_id_proof_type', models.CharField(blank=True, choices=[('DRIVING LICENSE', 'DRIVING LICENSE'), ('F AND B LICENSE', 'F AND B LICENSE')], max_length=20, null=True)),
                ('id_proof_type_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('id_proof_file', models.FileField(blank=True, null=True, upload_to='ID_PROOF/')),
                ('validity', models.DateTimeField(blank=True, null=True)),
                ('nsr', models.FileField(blank=True, null=True, upload_to='PCC/')),
                ('pcc', models.FileField(blank=True, null=True, upload_to='NSR/')),
                ('is_complete', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('ratings', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True)),
                ('suggest_to_improve', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved by Senior', 'Approved by Senior'), ('Approved by HR', 'Approved by HR'), ('Resigned', 'Resigned')], default='Active', max_length=20)),
                ('resignation_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved by Senior', 'Approved by Senior'), ('Approved by HR', 'Approved by HR'), ('Resigned', 'Resigned')], default='Pending', max_length=20)),
                ('senior_approval', models.BooleanField(default=False)),
                ('hr_approval', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Paid Leave', 'Paid Leave')], max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('reason', models.CharField(max_length=120, null=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaverequest', to='hr_app.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ot', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('leave_plus', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('medical', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('ta', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('food_allowance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('canteen_expense', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('pf', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('esi', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('bonuses', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.employeedetails')),
            ],
        ),
    ]
