# Generated by Django 4.2.12 on 2024-12-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_alter_employeedetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS'), ('PREFER NOT TO SAY', 'PREFER NOT TO SAY')], max_length=20, null=True),
        ),
    ]
