# Generated by Django 4.2.12 on 2024-11-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_remove_employeedetails_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='employee_esi_no',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='pf_no',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True),
        ),
    ]
