# Generated by Django 4.2.12 on 2024-11-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_alter_employeedetails_employee_esi_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='bank_details',
            field=models.FileField(blank=True, null=True, upload_to='BANK/'),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='RESUME/'),
        ),
    ]
