# Generated by Django 4.2.12 on 2024-12-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_publicholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicholiday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='publicholiday',
            name='name',
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
