# Generated by Django 4.2.12 on 2024-12-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_remove_publicholiday_date_remove_publicholiday_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicholiday',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='publicholiday',
            name='start_date',
        ),
    ]
