# Generated by Django 4.2.12 on 2024-12-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_rename_end_date_publicholiday_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
