# Generated by Django 4.2.4 on 2024-11-29 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dealer_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=100, null=True)),
                ('dealer_nbr', models.BigIntegerField(null=True)),
                ('dealer_address', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('destination', models.CharField(max_length=250, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=200, null=True)),
                ('aadhaar_number', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('license_exp_date', models.DateField(null=True)),
                ('upload_license', models.ImageField(null=True, upload_to='images/')),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('ratings', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privatevehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclename', models.CharField(max_length=250, null=True)),
                ('driver', models.CharField(max_length=200, null=True)),
                ('nbr', models.BigIntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('remarks', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200, null=True)),
                ('starting_point', models.CharField(max_length=200, null=True)),
                ('ending_point', models.CharField(max_length=200, null=True)),
                ('total_distance', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200, null=True)),
                ('vehicle_nbr', models.CharField(max_length=200, null=True)),
                ('vehicle_img', models.ImageField(null=True, upload_to='images/')),
                ('vehicle_insurance_date', models.DateField(null=True)),
                ('vehicle_taxes_date', models.DateField(null=True)),
                ('vehicle_fasttag', models.IntegerField(null=True)),
                ('vehicle_pollution_date', models.DateField(null=True)),
                ('vehicle_capacity', models.IntegerField(null=True)),
                ('vehicle_rate', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeofMaintenance', models.CharField(choices=[('Fuel ', 'Fuel'), ('FastTag', 'FastTag'), ('Tyre', 'Tyre'), ('Oil', 'Oil'), ('Insurance', 'Insurance'), ('Pollution', 'Pollution'), ('Tax', 'Tax'), ('CommonRepair', 'CommonRepair')], max_length=20, null=True)),
                ('amount', models.FloatField(default=0.0, null=True)),
                ('Remarks', models.CharField(max_length=250, null=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='trackorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('number', models.IntegerField(null=True)),
                ('quantity', models.BigIntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=200, null=True)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.dealer_reg')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods')),
            ],
        ),
        migrations.CreateModel(
            name='Route_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('percasecost', models.FloatField(default=0.0, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('dealer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.dealer_reg')),
                ('driver', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.driver')),
                ('route', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.route')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='logistics_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.driver')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.route')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods')),
            ],
        ),
    ]
