# Generated by Django 5.0.6 on 2024-11-29 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics_app', '0001_initial'),
        ('production_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchadvice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logistics_report',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.driver'),
        ),
        migrations.AddField(
            model_name='logistics_report',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods'),
        ),
        migrations.AddField(
            model_name='logistics_report',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.route'),
        ),
        migrations.AddField(
            model_name='route_plan',
            name='dealer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.dealer_reg'),
        ),
        migrations.AddField(
            model_name='route_plan',
            name='driver',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.driver'),
        ),
        migrations.AddField(
            model_name='route_plan',
            name='route',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.route'),
        ),
        migrations.AddField(
            model_name='dispatchadvice',
            name='route_plan',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.route_plan'),
        ),
        migrations.AddField(
            model_name='trackorder',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.dealer_reg'),
        ),
        migrations.AddField(
            model_name='trackorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods'),
        ),
        migrations.AddField(
            model_name='route_plan',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle_maintenance',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.vehicle'),
        ),
    ]
