# Generated by Django 4.1.3 on 2024-11-28 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_app', '0001_initial'),
        ('logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchadvice',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.dealer_reg'),
        ),
        migrations.AddField(
            model_name='dispatchadvice',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods'),
        ),
        migrations.AddField(
            model_name='dispatchadvice',
            name='route_plan',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_app.route_plan'),
        ),
        migrations.AddField(
            model_name='dispatchadvice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
