# Generated by Django 4.2.4 on 2024-11-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_finished_good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('size', models.CharField(max_length=150, null=True, unique=True)),
                ('unit', models.CharField(max_length=150, null=True, unique=True)),
                ('unit_define', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('total_stock', models.IntegerField(default=0)),
                ('total_damaged', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Add_RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('size', models.CharField(max_length=150, null=True)),
                ('color', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('total_stock', models.IntegerField(default=0)),
                ('total_damaged_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Add_semi_finished_good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('size', models.CharField(max_length=150, null=True, unique=True)),
                ('unit', models.CharField(max_length=150, null=True, unique=True)),
                ('unit_define', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('total_stock', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, null=True)),
                ('material_type', models.CharField(choices=[('Raw Materials', 'Raw Materials'), ('Finished Goods', 'Finished Goods'), ('Semi Finished Goods', 'Semi Finished Goods')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Damaged_Goods_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Goods_allocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Goods_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('response', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Goods_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_request_raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField()),
                ('required_date', models.DateField()),
                ('remarks', models.TextField()),
                ('requested_by', models.CharField(max_length=150, null=True)),
                ('verified_by', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_request_semi_finished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField()),
                ('required_date', models.DateField()),
                ('remarks', models.TextField()),
                ('requested_by', models.CharField(max_length=150, null=True)),
                ('verified_by', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material_allocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('input_date', models.DateField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(default='')),
                ('status', models.CharField(max_length=155, null=True)),
                ('response', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('response', models.TextField(blank=True, default='', null=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_entry', models.IntegerField(default=0)),
                ('damaged_entry_stock', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('raw_materials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_raw_materials', to='inventory_app.add_rawmaterial')),
            ],
        ),
    ]
