# Generated by Django 5.0.6 on 2024-11-28 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_Goods_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material_allocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('input_date', models.DateField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(default='')),
                ('status', models.CharField(max_length=155, null=True)),
                ('response', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('response', models.TextField(blank=True, default='', null=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Damaged_Goods_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('damaged', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production_app.damaged_goods')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Goods_allocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(default='')),
                ('finished_good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Goods_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('response', models.TextField(blank=True, default='', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods_category')),
            ],
        ),
    ]
