# Generated by Django 5.0.6 on 2024-11-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_app', '0001_initial'),
        ('production_app', '0001_initial'),
        ('purchase_app', '0001_initial'),
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_goods_request',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.department'),
        ),
        migrations.AddField(
            model_name='finished_goods_request',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods'),
        ),
        migrations.AddField(
            model_name='finished_goods_stock',
            name='finished_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production_app.water_finished_goods'),
        ),
        migrations.AddField(
            model_name='purchase_request_raw_material',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_request', to='inventory_app.addcategory'),
        ),
        migrations.AddField(
            model_name='purchase_request_raw_material',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_request', to='register_app.department'),
        ),
        migrations.AddField(
            model_name='purchase_request_raw_material',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_request', to='inventory_app.add_rawmaterial'),
        ),
        migrations.AddField(
            model_name='purchase_request_semi_finished',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_request_semi', to='inventory_app.addcategory'),
        ),
        migrations.AddField(
            model_name='purchase_request_semi_finished',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_semi_request', to='register_app.department'),
        ),
        migrations.AddField(
            model_name='purchase_request_semi_finished',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_request_semi', to='inventory_app.add_semi_finished_good'),
        ),
        migrations.AddField(
            model_name='raw_material_allocate',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.rawmaterials'),
        ),
        migrations.AddField(
            model_name='raw_material_request',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.rawmaterialcategory'),
        ),
        migrations.AddField(
            model_name='raw_material_request',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.department'),
        ),
        migrations.AddField(
            model_name='raw_material_request',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.rawmaterials'),
        ),
        migrations.AddField(
            model_name='rawmaterialsstock',
            name='raw_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='purchase_app.rawmaterials'),
        ),
        migrations.AddField(
            model_name='rawmaterialstock',
            name='raw_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_raw_materials', to='inventory_app.add_rawmaterial'),
        ),
    ]
