# Generated by Django 4.2.4 on 2024-11-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_app', '0001_initial'),
        ('inventory_app', '0002_initial'),
        ('purchase_app', '0001_initial'),
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_material_request',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.department'),
        ),
        migrations.AddField(
            model_name='raw_material_request',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.rawmaterials'),
        ),
        migrations.AddField(
            model_name='raw_material_allocate',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.rawmaterials'),
        ),
        migrations.AddField(
            model_name='purchase_request_semi_finished',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_request_semi', to='inventory_app.addcategory'),
        ),
        migrations.AddField(
            model_name='purchase_request_semi_finished',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_semi_request', to='register_app.department'),
        ),
        migrations.AddField(
            model_name='purchase_request_semi_finished',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_request_semi', to='inventory_app.add_semi_finished_good'),
        ),
        migrations.AddField(
            model_name='purchase_request_raw_material',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_request', to='inventory_app.addcategory'),
        ),
        migrations.AddField(
            model_name='purchase_request_raw_material',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_request', to='register_app.department'),
        ),
        migrations.AddField(
            model_name='purchase_request_raw_material',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_request', to='inventory_app.add_rawmaterial'),
        ),
        migrations.AddField(
            model_name='finished_goods_stock',
            name='finished_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production_app.water_finished_goods'),
        ),
        migrations.AddField(
            model_name='finished_goods_request',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods_category'),
        ),
        migrations.AddField(
            model_name='finished_goods_request',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.department'),
        ),
        migrations.AddField(
            model_name='finished_goods_request',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods'),
        ),
        migrations.AddField(
            model_name='finished_goods_allocate',
            name='finished_good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.water_finished_goods'),
        ),
        migrations.AddField(
            model_name='damaged_goods_stock',
            name='damaged',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production_app.damaged_goods'),
        ),
        migrations.AddField(
            model_name='add_semi_finished_good',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semi_finished_goods_category', to='inventory_app.addcategory'),
        ),
        migrations.AddField(
            model_name='add_semi_finished_good',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semi_finished_goods_type', to='inventory_app.addcategory'),
        ),
        migrations.AddField(
            model_name='add_rawmaterial',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_raw_materials', to='inventory_app.addcategory'),
        ),
        migrations.AddField(
            model_name='add_finished_good',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods_category', to='inventory_app.addcategory'),
        ),
    ]
