# Generated by Django 4.1.2 on 2024-11-29 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, null=True)),
                ('material_type', models.CharField(choices=[('Raw Materials', 'Raw Materials'), ('Finished Goods', 'Finished Goods'), ('Semi Finished Goods', 'Semi Finished Goods')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('size', models.CharField(max_length=150, null=True)),
                ('color', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('total_stock', models.IntegerField(default=0)),
                ('total_damaged_stock', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_raw_materials', to='inventory_app.addcategory')),
            ],
        ),
    ]
