# Generated by Django 5.0.6 on 2024-11-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_addcategory_add_rawmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcategory',
            name='material_type',
            field=models.CharField(choices=[('Raw Materials', 'Raw Materials'), ('Finished Goods', 'Finished Goods'), ('Semi Finished Goods', 'Semi Finished Goods')], max_length=50, null=True),
        ),
    ]
