# Generated by Django 5.0.6 on 2024-11-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_addcategory_material_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_RawMaterial',
        ),
        migrations.DeleteModel(
            name='AddCategory',
        ),
    ]
