# Generated by Django 4.1 on 2024-11-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_app", "0006_addcategory_add_rawmaterial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_rawmaterial",
            name="damaged_entry_stock",
        ),
        migrations.RemoveField(
            model_name="add_rawmaterial",
            name="stock_entry",
        ),
        migrations.AddField(
            model_name="add_rawmaterial",
            name="material_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_raw_materials",
                to="inventory_app.addcategory",
            ),
        ),
        migrations.AddField(
            model_name="add_rawmaterial",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="add_rawmaterial",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_raw_materials",
                to="inventory_app.addcategory",
            ),
        ),
        migrations.AlterField(
            model_name="add_rawmaterial",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="RawMaterialStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_entry", models.IntegerField(default=0)),
                ("damaged_entry_stock", models.IntegerField(default=0)),
                ("date", models.DateField(auto_now=True)),
                ("time", models.TimeField(auto_now_add=True)),
                (
                    "raw_materials",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_raw_materials",
                        to="inventory_app.add_rawmaterial",
                    ),
                ),
            ],
        ),
    ]
