# Generated by Django 4.1 on 2024-11-28 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_app", "0007_remove_add_rawmaterial_damaged_entry_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_rawmaterial",
            name="material_type",
        ),
    ]
