# Generated by Django 4.1 on 2024-11-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("register_app", "0001_initial"),
        ("inventory_app", "0008_remove_add_rawmaterial_material_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_semi_finished_good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=150, null=True, unique=True),
                ),
                ("size", models.CharField(max_length=150, null=True, unique=True)),
                ("unit", models.CharField(max_length=150, null=True, unique=True)),
                ("unit_define", models.IntegerField(null=True)),
                ("image", models.ImageField(null=True, upload_to="images/")),
                ("total_stock", models.IntegerField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semi_finished_goods_category",
                        to="inventory_app.addcategory",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semi_finished_goods_type",
                        to="inventory_app.addcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase_request_semi_finished",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_required", models.IntegerField()),
                ("required_date", models.DateField()),
                ("remarks", models.TextField()),
                ("requested_by", models.CharField(max_length=150, null=True)),
                ("verified_by", models.CharField(max_length=150, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=220)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_request_semi",
                        to="inventory_app.addcategory",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_semi_request",
                        to="register_app.department",
                    ),
                ),
                (
                    "product_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_request_semi",
                        to="inventory_app.add_semi_finished_good",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase_request_raw_material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_required", models.IntegerField()),
                ("required_date", models.DateField()),
                ("remarks", models.TextField()),
                ("requested_by", models.CharField(max_length=150, null=True)),
                ("verified_by", models.CharField(max_length=150, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=220)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_request",
                        to="inventory_app.addcategory",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_request",
                        to="register_app.department",
                    ),
                ),
                (
                    "product_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_request",
                        to="inventory_app.add_rawmaterial",
                    ),
                ),
            ],
        ),
    ]
