# Generated by Django 4.1 on 2024-11-29 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_app", "0009_add_semi_finished_good_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_finished_good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=150, null=True, unique=True),
                ),
                ("size", models.CharField(max_length=150, null=True, unique=True)),
                ("unit", models.CharField(max_length=150, null=True, unique=True)),
                ("unit_define", models.IntegerField(null=True)),
                ("image", models.ImageField(null=True, upload_to="images/")),
                ("date", models.DateField(auto_now_add=True, null=True)),
                ("time", models.TimeField(auto_now_add=True, null=True)),
                ("total_stock", models.IntegerField(default=0)),
                ("total_damaged", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finished_goods_category",
                        to="inventory_app.addcategory",
                    ),
                ),
            ],
        ),
    ]
