# Generated by Django 4.1 on 2024-11-29 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_app", "0010_add_finished_good"),
    ]

    operations = [
        migrations.RenameField(
            model_name="add_finished_good",
            old_name="product_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="add_semi_finished_good",
            old_name="product_name",
            new_name="name",
        ),
    ]
