# Generated by Django 4.1.2 on 2024-11-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emp_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
