# Generated by Django 4.1.2 on 2024-11-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0002_customuser_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='emp_id',
            new_name='unique_id',
        ),
    ]
