# Generated by Django 4.1.2 on 2024-11-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0003_rename_emp_id_customuser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
