# Generated by Django 5.0.6 on 2024-11-29 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0001_initial'),
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq_raw_materials',
            name='vendor_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_list_rfq', to='vendor_app.vendor_register'),
        ),
    ]
