# Generated by Django 4.1 on 2024-11-29 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_app", "0009_add_semi_finished_good_and_more"),
        ("purchase_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFQ_raw_materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfq_number", models.CharField(max_length=50, unique=True)),
                ("request_date", models.DateField(auto_now_add=True)),
                ("request_time", models.TimeField(auto_now_add=True)),
                ("requested_by", models.CharField(max_length=220, null=True)),
                ("approver", models.CharField(max_length=220, null=True)),
                ("quantity_needed", models.IntegerField()),
                ("batch_requirements", models.TextField(blank=True, null=True)),
                (
                    "quality_standards",
                    models.FileField(
                        blank=True, null=True, upload_to="quality_standards/"
                    ),
                ),
                ("expected_delivery_date", models.DateField()),
                ("vendor_list", models.TextField(null=True)),
                ("preferred_vendors", models.TextField(null=True)),
                ("quotation_deadline", models.DateField()),
                ("delivery_address", models.TextField()),
                ("spoc_name", models.CharField(max_length=220, null=True)),
                ("spoc_number", models.IntegerField()),
                ("special_notes", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=220)),
                (
                    "material_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfq_raw_material_category",
                        to="inventory_app.addcategory",
                    ),
                ),
                (
                    "material_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfq_raw_material_name",
                        to="inventory_app.add_rawmaterial",
                    ),
                ),
            ],
        ),
    ]
