# Generated by Django 4.1 on 2024-11-29 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_app", "0003_rfq_raw_materials_chumma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rfq_raw_materials",
            name="chumma",
        ),
    ]
