# Generated by Django 5.0.6 on 2024-11-29 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0003_remove_rfq_raw_materials_vendor_list_and_more'),
        ('vendor_app', '0002_vendor_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('po_date', models.DateField(auto_now_add=True)),
                ('po_time', models.TimeField(auto_now_add=True)),
                ('requested_by', models.CharField(max_length=150, null=True)),
                ('verified_by', models.CharField(max_length=150, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('po_status', models.CharField(max_length=10)),
                ('quotation_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='vendor_app.vendor_quotation')),
            ],
        ),
    ]
