# Generated by Django 4.1 on 2024-11-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_app", "0004_remove_rfq_raw_materials_chumma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfq_raw_materials",
            name="spoc_number",
            field=models.BigIntegerField(),
        ),
    ]
