# Generated by Django 4.1 on 2024-11-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_app", "0005_alter_rfq_raw_materials_spoc_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfq_raw_materials",
            name="rfq_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
