# Generated by Django 4.2 on 2024-11-28 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.ImageField(null=True, upload_to='images/')),
                ('remarks', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vendor', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('vendor_district', models.CharField(max_length=150, null=True)),
                ('vendor_state', models.CharField(max_length=200, null=True)),
                ('vendor_country', models.CharField(max_length=150, null=True)),
                ('vendor_pincode', models.IntegerField(null=True)),
                ('pan_yes_or_no', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10, null=True)),
                ('vendor_PANNBR', models.CharField(blank=True, max_length=150, null=True)),
                ('vendor_Street', models.CharField(max_length=200, null=True)),
                ('vendor_Landmark', models.CharField(max_length=200, null=True)),
                ('vendor_Building', models.CharField(max_length=200, null=True)),
                ('vendor_listofpdcts', models.CharField(max_length=150, null=True)),
                ('materials', models.ManyToManyField(to='purchase_app.rawmaterials')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
