# Generated by Django 4.1.2 on 2024-11-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_register',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
