# Generated by Django 5.0.6 on 2024-11-29 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0003_remove_rfq_raw_materials_vendor_list_and_more'),
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_Price', models.CharField(max_length=150, null=True)),
                ('total_Price', models.IntegerField(null=True)),
                ('discount', models.CharField(max_length=150, null=True)),
                ('payment_terms', models.CharField(max_length=150, null=True)),
                ('document', models.ImageField(null=True, upload_to='images/')),
                ('time_frame', models.CharField(max_length=150, null=True)),
                ('special_notes', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(max_length=150, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.rfq_raw_materials')),
            ],
        ),
    ]
