# Generated by Django 4.1.2 on 2024-11-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0001_initial'),
        ('vendor_app', '0002_vendor_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_register',
            name='materials',
            field=models.ManyToManyField(blank=True, to='purchase_app.rawmaterials'),
        ),
    ]
