# Generated by Django 4.1.2 on 2024-11-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_addcategory_add_rawmaterial'),
        ('vendor_app', '0005_remove_vendor_register_vendor_listofpdcts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_register',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, to='inventory_app.add_rawmaterial'),
        ),
    ]
