# Generated by Django 4.1.2 on 2024-11-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_addcategory_add_rawmaterial'),
        ('vendor_app', '0007_rename_materials_vendor_register_materials_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_register',
            name='status',
        ),
        migrations.AlterField(
            model_name='vendor_register',
            name='materials_name',
            field=models.ManyToManyField(blank=True, to='inventory_app.add_rawmaterial'),
        ),
    ]
